//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherTestApp.Resources.Languages {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WeatherTestApp.Resources.Languages.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        internal static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        internal static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        internal static string FavouriteTownsPage_Title {
            get {
                return ResourceManager.GetString("FavouriteTownsPage_Title", resourceCulture);
            }
        }
        
        internal static string WeatherByTownPage_Title {
            get {
                return ResourceManager.GetString("WeatherByTownPage_Title", resourceCulture);
            }
        }
        
        internal static string Menu_Favourite {
            get {
                return ResourceManager.GetString("Menu_Favourite", resourceCulture);
            }
        }
        
        internal static string Common_Menu {
            get {
                return ResourceManager.GetString("Common_Menu", resourceCulture);
            }
        }
        
        internal static string Common_WeatherApiTownSearchRequest {
            get {
                return ResourceManager.GetString("Common_WeatherApiTownSearchRequest", resourceCulture);
            }
        }
        
        internal static string WeatherByTownPage_NoTownDataFound {
            get {
                return ResourceManager.GetString("WeatherByTownPage_NoTownDataFound", resourceCulture);
            }
        }
        
        internal static string WeatherByTownPage_TownEntryPlaceholder {
            get {
                return ResourceManager.GetString("WeatherByTownPage_TownEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string WeatherByTownPage_Search {
            get {
                return ResourceManager.GetString("WeatherByTownPage_Search", resourceCulture);
            }
        }
        
        internal static string Common_FillAllEntries {
            get {
                return ResourceManager.GetString("Common_FillAllEntries", resourceCulture);
            }
        }
        
        internal static string Common_Celsius {
            get {
                return ResourceManager.GetString("Common_Celsius", resourceCulture);
            }
        }
        
        internal static string Common_Empty {
            get {
                return ResourceManager.GetString("Common_Empty", resourceCulture);
            }
        }
    }
}
